services:
  frontend:
    build:
      context: ./frontend # папка, где лежит проект NextJS
      dockerfile: DockerFile # имя Dockerfile внутри frontend
    container_name: solvee-laser-frontend
    env_file:
      - ./frontend/.env.production # подключаем env файл
    ports:
      - "3000:3000" # проброс порта наружу
    restart: unless-stopped #авто рестарт контейнера, если упадет
